openapi: 3.0.0 # need this as first line to allow some IDEs to know this is an openapi document.
# All endpoints defined here will be discoverable by all users. If there is a need to keep some endpoints "private", add them to the "managed-services-api-private.yaml" file
info:
  title: Red Hat Advanced Cluster Security Service Fleet Manager
  version: 1.2.0
  description: Red Hat Advanced Cluster Security (RHACS) Service Fleet Manager is a Rest API to manage instances of ACS components.
servers:
  - url: https://api.openshift.com
    description: Main (production) server
  - url: https://api.stage.openshift.com
    description: Staging server
  - url: http://localhost:8000
    description: localhost
  - url: /
    description: current domain
paths:
  /api/rhacs/v1:
    get:
      operationId: getVersionMetadata
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionMetadata'
          description: Version metadata
      summary: Returns the version metadata

  /api/rhacs/v1/errors/{id}:
    get:
      operationId: getErrorById
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Get error by Id
      summary: Returns the error by id
      tags:
        - errors
      parameters:
        - $ref: "#/components/parameters/id"

  /api/rhacs/v1/errors:
    get:
      operationId: getErrors
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
          description: List of possible errors
      summary: Returns the list of possible API errors
      tags:
        - errors

  /api/rhacs/v1/status:
    get:
      operationId: getServiceStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceStatus'
          description: Ok
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
      summary: Returns the status of resources, such as whether maximum service capacity has been reached
      security:
        - Bearer: [ ]
  /api/rhacs/v1/centrals/{id}:
    get:
      operationId: getCentralById
      description: This operation is only authorized to users in the same organisation as the owner organisation of this Central.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralRequest'
              examples:
                CentralRequestGetResponseExample:
                  $ref: '#/components/examples/CentralRequestExample'
                CentralRequestGetResponseWithFailedCreationStatusExample:
                  $ref: '#/components/examples/CentralRequestFailedCreationStatusExample'
          description: Central request found by ID
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                403Example:
                  $ref: '#/components/examples/403Example'
          description: User not authorized to access the service
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          description: No Central request with specified ID exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: Unexpected error occurred
      security:
        - Bearer: [ ]
      summary: Returns a Central request by ID
    delete:
      operationId: deleteCentralById
      description: The only users authorized for this operation are 1) the administrator of the owner organisation of this Central; and 2) the owner user only if it is also part of the owner organisation.
      parameters:
        - in: query
          name: async
          description: Perform the action in an asynchronous manner
          schema:
            type: boolean
          required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
              #No Content
          description: Deleted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                400DeletionExample:
                  $ref: '#/components/examples/400DeletionExample'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                403Example:
                  $ref: '#/components/examples/403Example'
          description: User not authorized to access the service
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404DeleteExample:
                  $ref: '#/components/examples/404DeleteExample'
          description: No Central request with specified ID exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500DeleteExample:
                  $ref: '#/components/examples/500DeleteExample'
          description: Unexpected error occurred
      summary: Deletes a Central request by ID
      security:
        - Bearer: [ ]
    patch:
      summary: Update a Central instance by id
      description: The only users authorized for this operation are 1) the administrator of the owner organisation of this Central; and 2) the owner user only if it is also part of the owner organisation.
      security:
        - Bearer: [ ]
      operationId: updateCentralById
      requestBody:
        description: Update owner of Central
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CentralUpdateRequest'
        required: true
      responses:
        "200":
          description: Central updated by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralRequest'
              examples:
                CentralRequestPostResponseExample:
                  $ref: '#/components/examples/CentralRequestExample'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: User is not authorised to access the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: No Central found with the specified ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    parameters:
      - $ref: "#/components/parameters/id"
  /api/rhacs/v1/centrals:
    post:
      operationId: createCentral
      description: Each central has a single owner organisation and a single owner user. Creates a new Central that is owned by the user and organisation authenticated for the request.
      parameters:
        - in: query
          name: async
          description: Perform the action in an asynchronous manner
          schema:
            type: boolean
          required: true
      requestBody:
        description: Central data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CentralRequestPayload'
            examples:
              USRegion:
                $ref: '#/components/examples/USRegionExample'
              EURegion:
                $ref: '#/components/examples/EURegionExample'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralRequest'
              examples:
                CentralRequestPostResponseExample:
                  $ref: '#/components/examples/CentralRequestExample'
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                400CreationExample:
                  $ref: '#/components/examples/400CreationExample'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                403Example:
                  $ref: '#/components/examples/403Example'
                403MaxAllowedInstanceReachedExample:
                  $ref: '#/components/examples/403MaxAllowedInstanceReachedExample'
                403TermsNotAcceptedExample:
                  $ref: '#/components/examples/403TermsNotAcceptedExample'
          description: User forbidden either because the user is not authorized to access the service or because the maximum number of instances that can be created by this user has been reached.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                404Example:
                  $ref: '#/components/examples/404Example'
          description: The requested resource doesn't exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                409NameConflictExample:
                  $ref: '#/components/examples/409NameConflictExample'
          description: A conflict has been detected in the creation of this resource
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
          description: An unexpected error occurred while creating the Central request
      security:
        - Bearer: [ ]
      summary: Creates a Central request
    get:
      summary: Returns a list of Central requests
      description: Only returns those centrals that are owned by the organisation of the user authenticated for the request.
      operationId: getCentrals
      security:
        - Bearer: [ ]
      responses:
        "200":
          description: A list of Central requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralRequestList'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                InvalidQueryExample:
                  $ref: '#/components/examples/400InvalidQueryExample'
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                403Example:
                  $ref: '#/components/examples/403Example'
          description: User not authorized to access the service
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/owner-user'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
  /api/rhacs/v1/cloud_providers:
    get:
      summary: Returns the list of supported cloud providers
      operationId: getCloudProviders
      security:
        - Bearer: [ ]
      responses:
        '200':
          description: Returned list of supported cloud providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudProviderList'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
  /api/rhacs/v1/cloud_providers/{id}/regions:
    get:
      summary: Returns the list of supported regions of the supported cloud provider
      operationId: getCloudProviderRegions
      security:
        - Bearer: [ ]
      responses:
        '200':
          description: Returned list of supported cloud provider regions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudRegionList'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                401Example:
                  $ref: '#/components/examples/401Example'
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                500Example:
                  $ref: '#/components/examples/500Example'
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/instance_type'

components:
  schemas:
    ObjectReference:
      type: object
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
      required:
        - id
        - kind
      discriminator:
        propertyName: kind          
    List:
      required:
        - kind
        - page
        - size
        - total
        - items
      type: object
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      discriminator:
        propertyName: kind
    Error:
      allOf:
        - $ref: "#/components/schemas/ObjectReference"
        - type: object
          properties:
            code:
              type: string
            reason:
              type: string
            operation_id:
              type: string
    ErrorList:
      allOf:
        - $ref: "#/components/schemas/List"
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Error"
    CentralRequest:
      allOf:
        - $ref: "#/components/schemas/ObjectReference"
        - type: object
          required:
            - multi_az
            - owner-organisation
          properties:
            status:
              description: "Values: [accepted, preparing, provisioning, ready, failed, deprovision, deleting] "
              type: string
            cloud_provider:
              description: "Name of Cloud used to deploy. For example AWS"
              type: string
            multi_az:
              type: boolean
            region:
              description: "Values will be regions of specific cloud provider. For example: us-east-1 for AWS"
              type: string
            owner-user:
              type: string
            owner-organisation:
              type: string
            name:
              type: string
            host:
              type: string
            created_at:
              format: date-time
              type: string
            updated_at:
              format: date-time
              type: string
            failed_reason:
              type: string
            version:
              type: string
            instance_type:
              type: string
          example:
            $ref: "#/components/examples/CentralRequestExample"
    CentralRequestList:
      allOf:
        - $ref: "#/components/schemas/List"
        - type: object
          example:
            kind: "CentralRequestList"
            page: "1"
            size: "1"
            total: "1"
            item:
              $ref: '#/components/examples/CentralRequestExample'
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: "#/components/schemas/CentralRequest"
    VersionMetadata:
      allOf:
        - $ref: "#/components/schemas/ObjectReference"
        - type: object
          example:
            kind: "APIVersion"
            id: "v1"
            href: "/api/rhacs/v1"
            collections:
              - id: "centrals"
                href: "/api/rhacs/v1/centrals"
                kind: "CentralList"
          properties:
            collections:
              type: array
              items:
                allOf:
                  - $ref: "#/components/schemas/ObjectReference"
    ServiceStatus:
      description: Schema for the service status response body
      example:
        centrals:
          max_capacity_reached: true
      type: object
      properties:
        centrals:
          description: The RHACS resource api status
          type: object
          required:
            - max_capacity_reached
          properties:
            max_capacity_reached:
              description: Indicates whether maximum service capacity has been reached
              type: boolean
    CentralRequestPayload:
      description: Schema for the request body sent to /centrals POST
      required:
        - name
      type: object
      properties:
        cloud_provider:
          description: The cloud provider where the RHACS Central component will be created in
          type: string
        multi_az:
          description: Set this to true to configure the RHACS Central component to be multiAZ
          type: boolean
        name:
          description: 'The name of the RHACS Central component. It must consist of lower-case alphanumeric characters or ''-'', start with an alphabetic character, and end with an alphanumeric character, and can not be longer than 32 characters.'
          type: string
        region:
          description: The region where the RHACS Central component will be created in
          type: string
    CloudProviderList:
      allOf:
        - $ref: "#/components/schemas/List"
        - type: object
          example:
            kind: "CloudProviderList"
            page: "1"
            size: "1"
            total: "1"
            item:
              $ref: '#/components/examples/CloudProviderExample'
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: "#/components/schemas/CloudProvider"
    CloudRegionList:
      allOf:
        - $ref: "#/components/schemas/List"
        - type: object
          example:
            kind: "CloudRegionList"
            page: "1"
            size: "1"
            total: "1"
            item:
              $ref: '#/components/examples/CloudRegionExample'
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: "#/components/schemas/CloudRegion"
    CloudProvider:
      description: 'Cloud provider.'
      properties:
        kind:
          description: 'Indicates the type of this object. Will be ''CloudProvider'' link.'
          type: string
        id:
          description: 'Unique identifier of the object.'
          type: string
        display_name:
          description: 'Name of the cloud provider for display purposes.'
          type: string
        name:
          description: 'Human friendly identifier of the cloud provider, for example `aws`.'
          type: string
        enabled:
          description: 'Whether the cloud provider is enabled for deploying an OSD cluster.'
          type: boolean
      required:
        - enabled
    CloudRegion:
      description: 'Description of a region of a cloud provider.'
      properties:
        kind:
          description: 'Indicates the type of this object. Will be ''CloudRegion''.'
          type: string
        id:
          description: 'Unique identifier of the object.'
          type: string
        display_name:
          description: 'Name of the region for display purposes, for example `N. Virginia`.'
          type: string
        enabled:
          description: 'Whether the region is enabled for deploying an OSD cluster.'
          type: boolean
          default: false
        supported_instance_types:
          description: 'The RHACS Central component instance types supported by this region.'
          type: array
          items: 
            type: string
      required:
        - enabled
        - supported_instance_types
    CentralUpdateRequest:
      type: object
      properties:
        # for now owner user is the only supported field for update
        owner-user:
          type: string
          nullable: true 

  parameters:
    id:
      name: id
      description: The ID of record
      schema:
        type: string
      in: path
      required: true
    filters:
      name: filters
      in: query
      description: List of metrics to fetch. Fetch all metrics when empty. List entries are Central internal metric names.
      schema:
        type: array
        items:
          type: string
        default: [ ]
    page:
      name: page
      in: query
      description: Page index
      required: false
      schema:
        type: string
      examples:
        page:
          value: "1"
    size:
      name: size
      in: query
      description: Number of items in each page
      required: false
      schema:
        type: string
      examples:
        size:
          value: "100"
    name:
      name: name
      in: query
      description: Name of the request
      required: false
      schema:
        type: string
    owner-user:
      name: owner-user
      in: query
      description: User that owns the request
      required: false
      schema:
        type: string
    instance_type:
      name: instance_type
      description: The Central instance type to filter the results by
      in: query
      schema:
        type: string
      required: false
      examples:
        eval_instance_type:
          value: "eval"
        standard_instance_type:
          value: "standard"
  securitySchemes:
    Bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  examples:
    USRegionExample:
      value:
        region: "us-east-1"
        cloud_provider: "aws"
        name: "serviceapitest"
    EURegionExample:
      value:
        region: "eu-west-1"
        cloud_provider: "aws"
        name: "serviceapitest"
    CentralRequestExample:
      value:
        id: "1iSY6RQ3JKI8Q0OTmjQFd3ocFRg"
        kind: "central"
        href: "/api/rhacs/v1/centrals/1iSY6RQ3JKI8Q0OTmjQFd3ocFRg"
        status: "ready"
        cloud_provider: "aws"
        multi_az: true
        region: "us-east-1"
        owner-user: "alice"
        owner-organisation: "my_org"
        name: "serviceapi"
        host: "serviceapi-1isy6rq3jki8q0otmjqfd3ocfrg.example.rhacs.com"
        created_at: "2020-10-05T12:51:24.053142Z"
        updated_at: "2020-10-05T12:56:36.362208Z"
        version: "2.6.0"
        instance_type: standard
    CentralRequestFailedCreationStatusExample:
      value:
        id: "1iSY6RQ3JKI8Q0OTmjQFd3ocFRg"
        kind: "central"
        href: "/api/rhacs/v1/centrals/1iSY6RQ3JKI8Q0OTmjQFd3ocFRg"
        status: "failed"
        cloud_provider: "aws"
        multi_az: true
        region: "us-east-1"
        owner-user: "bob"
        owner-organisation: "my_org"
        name: "serviceapi"
        host: "serviceapi-1isy6rq3jki8q0otmjqfd3ocfrg.example.rhacs.com"
        created_at: "2020-10-05T12:51:24.053142Z"
        updated_at: "2020-10-05T12:56:36.362208Z"
        failed_reason: "a reason the Central request creation failed"
        instance_type: standard
    CloudProviderExample:
      value:
        kind: "CloudProvider"
        id: "aws"
        name: "aws"
        display_name: "Amazon Web Services"
        enabled: true
    CloudRegionExample:
      value:
        kind: "CloudRegion"
        id: "us-east-1"
        display_name: "US East, N. Virginia"
        enabled: true
        supported_instance_types: ["standard", "eval"]
    MetricsRangeQueryExample:
      value:
        metric:
          __name__: central_server_brokertopicmetrics_bytes_in_total
          central_operator_io_cluster: central-service
          topic: __consumer_offsets
        values:
          - timestamp: 1611670230000
            value: 84154
          - timestamp: 1611670260000
            value: 85888
          - timestamp: 1611670290000
            value: 87622
    MetricsInstantQueryExample:
      value:
        metric:
          __name__: central_server_brokertopicmetrics_bytes_in_total
          central_operator_io_cluster: central-service
          topic: __consumer_offsets
        timestamp: 1611670230000
        value: 84154
    400DeletionExample:
      value:
        id: "103"
        kind: "Error"
        href: "/api/rhacs/v1/errors/103"
        code: "CENTRALS-MGMT-103"
        reason: "Synchronous action is not supported, use async=true parameter"
        operation_id: "1iWIimqGcrDuL61aUxIZqBTqNRa"
    400CreationExample:
      value:
        id: "103"
        kind: "Error"
        href: "/api/rhacs/v1/errors/103"
        code: "CENTRALS-MGMT-103"
        reason: "Synchronous action is not supported, use async=true parameter"
        operation_id: "1iWIimqGcrDuL61aUxIZqBTqNRa"
    400MissingParameterExample:
      value:
        id: "21"
        kind: "Error"
        href: "/api/rhacs/v1/errors/21"
        code: "CENTRALS-MGMT-21"
        reason: "missing path parameter: central id"
        operation_id: "1lWDGuybIrEnxrAem724gqkkiDv"
    404Example:
      value:
        id: "7"
        kind: "Error"
        href: "/api/rhacs/v1/errors/7"
        code: "CENTRALS-MGMT-7"
        reason: "The requested resource doesn't exist"
    404DeleteExample:
      value:
        id: "7"
        kind: "Error"
        href: "/api/rhacs/v1/errors/7"
        code: "CENTRALS-MGMT-7"
        reason: "CentralResource with id='1iK3duVYIvv5YvLlyz1mGR3JyqN' not found"
        operation_id: "1iYO7g2g6HTdUKUa2ksH82kQD3y"
    401Example:
      value:
        id: "11"
        kind: "Error"
        href: "/api/rhacs/v1/errors/11"
        code: "CENTRALS-MGMT-11"
        reason: "Unable to verify JWT token: Required authorization token not found"
        operation_id: "1iY3UhEhwmXBpWPfI2lNekpd4ZD"
    403Example:
      value:
        id: "4"
        kind: "Error"
        href: "/api/rhacs/v1/errors/4"
        code: "CENTRALS-MGMT-4"
        reason: "User 'foo-bar' is not authorized to access the service."
        operation_id: "1lY3UiEhznXBpWPfI2lNejpd4YC"
    403MaxAllowedInstanceReachedExample:
      value:
        id: "5"
        kind: "Error"
        href: "/api/rhacs/v1/errors/5"
        code: "CENTRALS-MGMT-5"
        reason: "User 'foo-bar' has reached a maximum number of 6 allowed instances."
        operation_id: "1lY3UiEkxnXBpVPeI2oNejd3XB"
    403TermsNotAcceptedExample:
      value:
        id: "12"
        kind: "Error"
        href: "/api/rhacs/v1/errors/12"
        code: "CENTRALS-MGMT-12"
        reason: "Required terms have not been accepted"
        operation_id: "kXCzWPeI2oXBpVPeI2LvF9jMQY"
    409NameConflictExample:
      value:
        id: "36"
        kind: "Error"
        href: "/api/rhacs/v1/errors/36"
        code: "CENTRALS-MGMT-36"
        reason: "Central component name is already used"
        operation_id: "6kY0UiEkzkXCzWPeI2oYehd3ED"
    500Example:
      value:
        id: "9"
        kind: "Error"
        href: "/api/rhacs/v1/errors/9"
        code: "CENTRALS-MGMT-9"
        reason: "Unspecified error"
        operation_id: "1ieELvF9jMQY6YghfM9gGRsHvEW"
    500DeleteExample:
      value:
        id: "9"
        kind: "Error"
        href: "/api/rhacs/v1/errors/9"
        code: "CENTRALS-MGMT-9"
        reason: "error deleting syncset: OCM-EX-9: failed to delete syncset: ext-serviceapi-1ix03lndlmq0qfc7sita5sljv8e
          for cluster id: 1g5d88q0lrcdv4g7alb7slfgnj3dhbsj%!(EXTRA *errors.Error=identifier
          is '404', code is 'CLUSTERS-MGMT-404' and operation identifier is '1g5or50viu07oealuehrkc26dgftj1ac':
          Cluster '1g5d88q0lrcdv4g7alb7slfgnj3dhbsj' not found)"
        operation_id: "1iYTsWry6nsqb2sNmFj5bXpD7Ca"
