openapi: 3.0.0
info:
  description: The admin APIs for the fleet manager of Dinosaur service
  title: Dinosaur Service Fleet Manager Admin APIs
  version: 0.0.2
servers:
- description: Main (production) server
  url: https://api.openshift.com
- description: Staging server
  url: https://api.stage.openshift.com
- description: localhost
  url: http://localhost:8000
- description: current domain
  url: /
tags:
- name: Admin APIs
paths:
  /api/dinosaurs_mgmt/v1/admin/dinosaurs:
    get:
      operationId: getDinosaurs
      parameters:
      - description: Page index
        examples:
          page:
            value: "1"
        in: query
        name: page
        required: false
        schema:
          type: string
      - description: Number of items in each page
        examples:
          size:
            value: "100"
        in: query
        name: size
        required: false
        schema:
          type: string
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the `order by` clause of an SQL statement.
          Each query can be ordered by any of the following `centralRequests` fields:

          * host
          * cloud_provider
          * cluster_id
          * created_at
          * href
          * id
          * instance_type
          * multi_az
          * name
          * organisation_id
          * owner
          * region
          * status
          * updated_at
          * version

          For example, to return all Central instances ordered by their name, use the following syntax:

          ```sql
          name asc
          ```

          To return all Central instances ordered by their name _and_ created date, use the following syntax:

          ```sql
          name asc, created_at asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          the results are ordered by name.
        examples:
          orderBy:
            value: name asc
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |
          Search criteria.

          The syntax of this parameter is similar to the syntax of the `where` clause of an
          SQL statement. Allowed fields in the search are `cloud_provider`, `name`, `owner`, `region`, and `status`. Allowed comparators are `<>`, `=`, or `LIKE`.
          Allowed joins are `AND` and `OR`. However, you can use a maximum of 10 joins in a search query.

          Examples:

          To return a Central instance with the name `my-central` and the region `aws`, use the following syntax:

          ```
          name = my-central and cloud_provider = aws
          ```[p-]

          To return a Central instance with a name that starts with `my`, use the following syntax:

          ```
          name like my%25
          ```

          If the parameter isn't provided, or if the value is empty, then all the Central instances
          that the user has permission to see are returned.

          Note. If the query is invalid, an error is returned.
        examples:
          search:
            value: name = my-central and cloud_provider = aws
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinosaurList'
          description: Return a list of Dinosaur instances. This endpoint will return
            all Dinosaur instances that are stored in the database and the are not
            filtered based on user ids or org ids.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User is not authorised to access the service
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of Dinosaurs
    post:
      description: |
        Each central has a single owner organisation and a single owner user. Creates a new Central that is owned by the user and organisation authenticated for the request.
        This API allows providing custom resource settings for the new Central instance.
      operationId: createCentral
      parameters:
      - description: Perform the action in an asynchronous manner
        explode: true
        in: query
        name: async
        required: true
        schema:
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CentralRequestPayload'
        description: Central data
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CentralRequest'
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User forbidden either because the user is not authorized to
            access the service or because the maximum number of instances that can
            be created by this user has been reached.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requested resource doesn't exist
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: A conflict has been detected in the creation of this resource
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error occurred while creating the Central request
      security:
      - Bearer: []
      summary: Creates a Central request
  /api/dinosaurs_mgmt/v1/admin/dinosaurs/{id}:
    delete:
      operationId: deleteDinosaurById
      parameters:
      - description: The ID of record
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Perform the action in an asynchronous manner
        explode: true
        in: query
        name: async
        required: true
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur updated by ID
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User is not authorised to access the service
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No Dinosaur found with the specified ID
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Delete a Dinosaur by ID
    get:
      operationId: getDinosaurById
      parameters:
      - description: The ID of record
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur found by ID
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User is not authorised to access the service
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No Dinosaur found with the specified ID
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Return the details of Dinosaur instance by id
    patch:
      operationId: updateDinosaurById
      parameters:
      - description: The ID of record
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DinosaurUpdateRequest'
        description: Dinosaur update data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur updated by ID
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: User is not authorised to access the service
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No Dinosaur found with the specified ID
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Update a Dinosaur instance by id
components:
  schemas:
    Dinosaur:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - required:
        - dinosaur_operator_upgrading
        - dinosaur_upgrading
        - multi_az
      - $ref: '#/components/schemas/Dinosaur_allOf'
    DinosaurList:
      allOf:
      - $ref: '#/components/schemas/List'
      - $ref: '#/components/schemas/DinosaurList_allOf'
    DinosaurUpdateRequest:
      example:
        dinosaur_version: dinosaur_version
        central:
          resources:
            requests:
              key: requests
            limits:
              key: limits
        scanner:
          analyzer:
            scaling:
              maxReplicas: 1
              autoScaling: autoScaling
              minReplicas: 1
              replicas: 1
            resources:
              requests:
                key: requests
              limits:
                key: limits
          db:
            resources:
              requests:
                key: requests
              limits:
                key: limits
        dinosaur_operator_version: dinosaur_operator_version
      properties:
        dinosaur_operator_version:
          type: string
        dinosaur_version:
          type: string
        central:
          $ref: '#/components/schemas/CentralSpec'
        scanner:
          $ref: '#/components/schemas/ScannerSpec'
      type: object
    Error:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - $ref: '#/components/schemas/Error_allOf'
    ObjectReference:
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
      type: object
    CentralRequestPayload:
      description: Schema for the request body sent to /centrals POST
      example:
        central:
          resources:
            requests:
              key: requests
            limits:
              key: limits
        multi_az: true
        name: name
        scanner:
          analyzer:
            scaling:
              maxReplicas: 1
              autoScaling: autoScaling
              minReplicas: 1
              replicas: 1
            resources:
              requests:
                key: requests
              limits:
                key: limits
          db:
            resources:
              requests:
                key: requests
              limits:
                key: limits
        cloud_provider: cloud_provider
        region: region
      properties:
        cloud_provider:
          description: The cloud provider where the Central component will be created
            in
          type: string
        multi_az:
          description: Set this to true to configure the Central component to be multiAZ
          type: boolean
        name:
          description: The name of the Central component. It must consist of lower-case
            alphanumeric characters or '-', start with an alphabetic character, and
            end with an alphanumeric character, and can not be longer than 32 characters.
          type: string
        region:
          description: The region where the Central component cluster will be created
            in
          type: string
        central:
          $ref: '#/components/schemas/CentralSpec'
        scanner:
          $ref: '#/components/schemas/ScannerSpec'
      required:
      - name
      type: object
    CentralSpec:
      example:
        resources:
          requests:
            key: requests
          limits:
            key: limits
      properties:
        resources:
          $ref: '#/components/schemas/ResourceRequirements'
      type: object
    ResourceRequirements:
      example:
        requests:
          key: requests
        limits:
          key: limits
      properties:
        requests:
          additionalProperties:
            type: string
          type: object
        limits:
          additionalProperties:
            type: string
          type: object
      type: object
    ResourceList:
      additionalProperties:
        type: string
      type: object
    ScannerSpec:
      example:
        analyzer:
          scaling:
            maxReplicas: 1
            autoScaling: autoScaling
            minReplicas: 1
            replicas: 1
          resources:
            requests:
              key: requests
            limits:
              key: limits
        db:
          resources:
            requests:
              key: requests
            limits:
              key: limits
      properties:
        analyzer:
          $ref: '#/components/schemas/ScannerSpec_analyzer'
        db:
          $ref: '#/components/schemas/ScannerSpec_db'
      type: object
    CentralRequest:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - $ref: '#/components/schemas/CentralRequest_allOf'
    List:
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
      - items
      - kind
      - page
      - size
      - total
      type: object
    Dinosaur_allOf_routes:
      properties:
        domain:
          type: string
        router:
          type: string
    Dinosaur_allOf:
      properties:
        status:
          description: 'Values: [accepted, preparing, provisioning, ready, failed,
            deprovision, deleting] '
          type: string
        cloud_provider:
          description: Name of Cloud used to deploy. For example AWS
          type: string
        multi_az:
          type: boolean
        region:
          description: 'Values will be regions of specific cloud provider. For example:
            us-east-1 for AWS'
          type: string
        owner:
          type: string
        name:
          type: string
        host:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        failed_reason:
          type: string
        actual_dinosaur_version:
          type: string
        actual_dinosaur_operator_version:
          type: string
        desired_dinosaur_version:
          type: string
        desired_dinosaur_operator_version:
          type: string
        dinosaur_upgrading:
          type: boolean
        dinosaur_operator_upgrading:
          type: boolean
        organisation_id:
          type: string
        subscription_id:
          type: string
        owner_account_id:
          type: string
        account_number:
          type: string
        instance_type:
          type: string
        quota_type:
          type: string
        routes:
          items:
            $ref: '#/components/schemas/Dinosaur_allOf_routes'
          type: array
        routes_created:
          type: boolean
        cluster_id:
          type: string
        namespace:
          type: string
        central:
          $ref: '#/components/schemas/CentralSpec'
        scanner:
          $ref: '#/components/schemas/ScannerSpec'
    DinosaurList_allOf:
      properties:
        items:
          items:
            allOf:
            - $ref: '#/components/schemas/Dinosaur'
          type: array
    Error_allOf:
      properties:
        code:
          type: string
        reason:
          type: string
        operation_id:
          type: string
    ScannerSpec_analyzer_scaling:
      example:
        maxReplicas: 1
        autoScaling: autoScaling
        minReplicas: 1
        replicas: 1
      properties:
        autoScaling:
          type: string
        replicas:
          format: int32
          minimum: 1
          type: integer
        minReplicas:
          format: int32
          minimum: 1
          type: integer
        maxReplicas:
          format: int32
          minimum: 1
          type: integer
    ScannerSpec_analyzer:
      example:
        scaling:
          maxReplicas: 1
          autoScaling: autoScaling
          minReplicas: 1
          replicas: 1
        resources:
          requests:
            key: requests
          limits:
            key: limits
      properties:
        resources:
          $ref: '#/components/schemas/ResourceRequirements'
        scaling:
          $ref: '#/components/schemas/ScannerSpec_analyzer_scaling'
    ScannerSpec_db:
      example:
        resources:
          requests:
            key: requests
          limits:
            key: limits
      properties:
        resources:
          $ref: '#/components/schemas/ResourceRequirements'
    CentralRequest_allOf:
      example: '{"$ref":"#/components/examples/CentralRequestExample"}'
      properties:
        status:
          description: 'Values: [accepted, preparing, provisioning, ready, failed,
            deprovision, deleting] '
          type: string
        cloud_provider:
          description: Name of Cloud used to deploy. For example AWS
          type: string
        multi_az:
          type: boolean
        region:
          description: 'Values will be regions of specific cloud provider. For example:
            us-east-1 for AWS'
          type: string
        owner:
          type: string
        name:
          type: string
        host:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
        failed_reason:
          type: string
        version:
          type: string
        instance_type:
          type: string
      required:
      - multi_az
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
